### ISSUE TITLE
How to use this library, it does not look complete, is s needed to cover the webrtc code to the full m120 branch?

### ISSUE THREAD

**Issue by zshaobo** [webrtcsdk/webrtcsdk#2]
How to use this library, it does not look complete, is s needed to cover the webrtc code to the full m120 branch?

**Comment by lambiengcode** [comment]
I successfully compiled aar for Android and xcframework for iOS. You can import in Android & iOS project to use:

## Android

![Maven Central](https://img.shields.io/maven-central/v/tech.waterbus/webrtc)

This library is hosted on Maven Central. To include this library in your project:

```gradle
  dependencies {
    implementation 'tech.waterbus:webrtc:120.6099.19'
  }
```

## iOS

Use the following lines near the top of your Podfile

```podspec
pod 'KaiRTC', '=120.6099.19'
```

if you wanna compile by your self, you also use repo [webrtc_build](https://github.com/webrtcsdk/webrtc-build) or compile by command following docs: https://github.com/webrtcsdk/webrtc-build/blob/main/docs/build.md

**Comment by lambiengcode** [comment]
it's full m120.6099 branch and it also have integrated end to end encryption, RNNoise, H265 Codec

**Comment by zshaobo** [comment]
think you  very much
